Time : 2023-01-29 17:43:29.171424
Exception : 'MainUI' object has no attribute 'main_subframe_left'
Traceback (most recent call last):
  File "d:\Python\PE_PBL\Project_GUI.py", line 1511, in <module>
    Main_frame=MainUI(root)
               ^^^^^^^^^^^^
  File "d:\Python\PE_PBL\Project_GUI.py", line 1134, in __init__
    self.configure_leftFrame()
  File "d:\Python\PE_PBL\Project_GUI.py", line 1161, in configure_leftFrame
    self.main_subframe_left, image=self.photo3, border=0, bg="white")
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainUI' object has no attribute 'main_subframe_left'

Time : 2023-01-29 18:22:03.155297
Exception : name 'Phone_num' is not defined
Traceback (most recent call last):
  File "d:\Python\PE_PBL\Project_GUI.py", line 1531, in <module>
    Main_frame=MainUI(root)
               ^^^^^^^^^^^^
  File "d:\Python\PE_PBL\Project_GUI.py", line 1151, in __init__
    self.getConfiguredName()
  File "d:\Python\PE_PBL\Project_GUI.py", line 1178, in getConfiguredName
    name=prj.ExtractName(Phone_num,'User')
                         ^^^^^^^^^
NameError: name 'Phone_num' is not defined

Time : 2023-01-29 18:22:41.535281
Exception : unknown font style "italic,bold"
Traceback (most recent call last):
  File "d:\Python\PE_PBL\Project_GUI.py", line 1531, in <module>
    Main_frame=MainUI(root)
               ^^^^^^^^^^^^
  File "d:\Python\PE_PBL\Project_GUI.py", line 1152, in __init__
    self.configure_leftFrame()
  File "d:\Python\PE_PBL\Project_GUI.py", line 1170, in configure_leftFrame
    self.name_label=Label(self.main_subframe_left,text=self.name,bg='white',font=('Times new roman',34,'italic,bold'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\2251075 SAKSHAM\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 3204, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "C:\Users\2251075 SAKSHAM\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2628, in __init__
    self.tk.call(
_tkinter.TclError: unknown font style "italic,bold"

Time : 2023-01-29 23:02:38.889421
Exception : expected integer but got "0.9"
Traceback (most recent call last):
  File "d:\Python\PE_PBL\Project_GUI.py", line 1585, in <module>
    Main_frame=MainUI(root)
               ^^^^^^^^^^^^
  File "d:\Python\PE_PBL\Project_GUI.py", line 1153, in __init__
    self.configure_topFrame()
  File "d:\Python\PE_PBL\Project_GUI.py", line 1242, in configure_topFrame
    Label(text=date_text,font='calibri 22 bold',height=0.9,bg='white').place(x=800,y=0)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\2251075 SAKSHAM\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 3204, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "C:\Users\2251075 SAKSHAM\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2628, in __init__
    self.tk.call(
_tkinter.TclError: expected integer but got "0.9"

